### ISSUE TITLE
AAD group as contributors

### ISSUE THREAD

**Issue by Sam-Rowe** [liamfoneill/AzureDevOpsBootstrap#1]

**Comment by Sam-Rowe** [comment]
Passed in to the terraform; populate the DevOps Contributors group from AAD group by name

**Comment by Sam-Rowe** [comment]
Looks like AAD Group to Azure DevOps group membership might need some refactoring

azuredevops_group_membership and azuredevops_group cannot be used at the same time :(

**Comment by Sam-Rowe** [comment]
https://www.terraform.io/docs/providers/azuredevops/r/group.html#members

**Comment by liamfoneill** [comment]
I think we will skip this for now. Having the admin will suffice
