### ISSUE TITLE
Service connection

### ISSUE THREAD

**Issue by Sam-Rowe** [liamfoneill/AzureDevOpsBootstrap#4]
Need to assume good naming convention

**Comment by Sam-Rowe** [comment]
Add a service connection to the new project via the Bootstrap terraform

**Comment by Sam-Rowe** [comment]
@liamfoneill can you setup some variables on the pipline please to test. I get a permission error when I try to add them.

I have amended the pipeline yaml as well as the variables.tf and the main.tf

subscription_id = Subscription ID of the Azure Sub created to host the new app
subscription_name = Subscription Name of the Azure Sub created to host the new app
tennant_id = tennant for the subscription

**Comment by liamfoneill** [comment]
all done. Works now!
